/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e8e1df',
        'surface-container-high': '#eee7e4',
        'on-primary-fixed-variant': '#584236',
        'background': '#fff8f6',
        'secondary': '#7c563f',
        'on-tertiary-fixed-variant': '#703537',
        'primary-container': '#443025',
        'surface-container': '#f4ecea',
        'surface-container-low': '#f9f2f0',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#33302e',
        'on-background': '#1e1b1a',
        'secondary-fixed': '#ffdbc8',
        'on-secondary-fixed-variant': '#613f2a',
        'surface-tint': '#71594d',
        'on-surface-variant': '#4f4540',
        'on-surface': '#1e1b1a',
        'surface-dim': '#dfd9d6',
        'primary-fixed': '#fddccc',
        'surface-bright': '#fff8f6',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb3b3',
        'inverse-on-surface': '#f6efed',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#b49789',
        'outline': '#81756f',
        'on-error-container': '#93000a',
        'tertiary-container': '#592326',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#390a0f',
        'on-tertiary-container': '#d58889',
        'on-secondary-container': '#78533d',
        'surface-variant': '#e8e1df',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#eebca0',
        'on-secondary-fixed': '#2f1504',
        'error': '#ba1a1a',
        'tertiary-fixed': '#ffdad9',
        'on-primary-fixed': '#28180e',
        'outline-variant': '#d3c3bd',
        'primary-fixed-dim': '#dfc0b0',
        'surface': '#fff8f6',
        'primary': '#2d1b11',
        'inverse-primary': '#dfc0b0',
        'on-secondary': '#ffffff',
        'tertiary': '#3e0e12',
        'secondary-container': '#fdcaad',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'grid-gutter': '24px',
        'section-gap-mobile': '64px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'container-padding': '32px',
        'section-gap-desktop': '120px',
      },
      fontFamily: {
        'headline-xl': ['"Source Serif 4"', 'serif'],
        'headline-lg': ['"Source Serif 4"', 'serif'],
        'headline-md': ['"Source Serif 4"', 'serif'],
        'headline-xl-mobile': ['"Source Serif 4"', 'serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
